### PR TITLE
Fix vxlan feature tests

### PR DESCRIPTION
**Pull request by robert-w-gries**
### N3k

``` bash
  1) Skipped:
TestFeature#test_vni [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:137]:
Skip test: Feature is unsupported on this device


  2) Skipped:
TestFeature#test_vn_segment_vlan_based [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:137]:
Skip test: Feature is unsupported on this device

13 runs, 42 assertions, 0 failures, 0 errors, 2 skips
```
### N6k Unsupported LC

``` bash
  1) Skipped:
TestFeature#test_fabric_forwarding [tests/test_feature.rb:89]:
This feature is only supported on 7.0(3)I2 images


  2) Skipped:
TestFeature#test_vn_segment_vlan_based [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:295]:
Unable to find compatible interface in chassis


  3) Skipped:
TestFeature#test_vni [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:295]:
Unable to find compatible interface in chassis


  4) Skipped:
TestFeature#test_nv_overlay [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:295]:
Unable to find compatible interface in chassis

13 runs, 34 assertions, 0 failures, 0 errors, 4 skips
```
### N7k F2 LC

``` bash
  1) Skipped:
TestFeature#test_vn_segment_vlan_based [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:279]:
Unable to find compatible interface in chassis


  2) Skipped:
TestFeature#test_fabric_forwarding [test_feature.rb:89]:
This feature is only supported on 7.0(3)I2 images


  3) Skipped:
TestFeature#test_vni [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:279]:
Unable to find compatible interface in chassis


  4) Skipped:
TestFeature#test_nv_overlay [/home/robgrie/cisco-network-node-utils/tests/ciscotest.rb:279]:
Unable to find compatible interface in chassis

13 runs, 36 assertions, 0 failures, 0 errors, 4 skips
```
### N7k F3 LC

``` bash
1) Skipped:
TestFeature#test_fabric_forwarding [tests/test_feature.rb:89]:
This feature is only supported on 7.0(3)I2 images


  2) Skipped:
TestFeature#test_vn_segment_vlan_based [tests/test_feature.rb:49]:
'feature','vn_segment_vlan_based' is unsupported on this node

13 runs, 44 assertions, 0 failures, 0 errors, 2 skips
```
### N9kv

``` bash
13 runs, 50 assertions, 0 failures, 0 errors, 0 skips
```

### CODE REVIEW

**Comment by robert-w-gries** [comment]
Before merging, I would like to test against stable N5k and supported N6k platforms.

**Comment by robert-w-gries** [comment]
N5k now passing consistently

``` bash
Node under test:
  - name  - n56-136
  - type  - N5K-C56128P
  - image - bootflash:///n6000-uk9.7.3.1.N1.1.bin

TestFeature#test_tacacs = 4.95 s = .
TestFeature#test_fabric_forwarding = 2.24 s = S
TestFeature#test_vtp = 4.68 s = .
TestFeature#test_nv_overlay = 15.75 s = .
TestFeature#test_bgp = 6.16 s = .
TestFeature#test_private_vlan = 3.60 s = .
TestFeature#test_feature_set_fabric = 34.67 s = .
TestFeature#test_vn_segment_vlan_based = 4.17 s = .
TestFeature#test_ospf = 3.15 s = .
TestFeature#test_feature_set_fex = 1.09 s = .
TestFeature#test_nv_overlay_evpn = 2.98 s = .
TestFeature#test_pim = 2.93 s = .
TestFeature#test_vni = 4.23 s = .

Finished in 93.251489s, 0.1394 runs/s, 0.4933 assertions/s.

  1) Skipped:
TestFeature#test_fabric_forwarding [tests/test_feature.rb:89]:
This feature is only supported on 7.0(3)I2 images

13 runs, 46 assertions, 0 failures, 0 errors, 1 skips
```

**Comment by chrisvanheuveln** [comment]
Your changes look okay. My only concern is that there may be some fallout from messing with these features. I see references in 7 providers:

```
bridge_domain_vni.rb:      Feature.vni_enable
encapsulation.rb:      return {} unless Feature.vni_enabled?
encapsulation.rb:      Feature.vni_enable
interface.rb:      Feature.vni_enable
interface_service_vni.rb:      Feature.vni_enable
interface_service_vni.rb:      Feature.vni_enable
vlan.rb:      Feature.vn_segment_vlan_based_enable
vrf.rb:      Feature.vn_segment_vlan_based_enable if platform == :nexus
vxlan_vtep.rb:      Feature.vn_segment_vlan_based_enable if VxlanVtep.mt_lite_support
```

It might be worthwhile to run the representative tests for these on a few platforms, like n3k-i2, n9k-i3, n5k, n7k.

**Comment by robert-w-gries** [comment]
Found and fixed bugs in `test_bridge_domain_vni` and `test_vxlan_vtep`.  Also verified no more N5k crashes for `test_vxlan_vtep`

### N5k

``` bash
Node under test:
  - name  - n56-136
  - type  - N5K-C56128P
  - image - bootflash:///n6000-uk9.7.3.0.N1.1.bin

TestVxlanVtep#test_source_interface = 17.85 s = .
TestVxlanVtep#test_shutdown = 16.86 s = .
TestVxlanVtep#test_create_destroy_one = 16.50 s = .
TestVxlanVtep#test_create_negative = 15.87 s = .
TestVxlanVtep#test_mt_full_create_destroy_multiple = 1.60 s = S
TestVxlanVtep#test_description = 16.01 s = .
TestVxlanVtep#test_host_reachability = 17.11 s = .
TestVxlanVtep#test_source_interface_hold_down_time = 15.13 s = .

Finished in 119.496320s, 0.0669 runs/s, 0.2092 assertions/s.

  1) Skipped:
TestVxlanVtep#test_mt_full_create_destroy_multiple [test_vxlan_vtep.rb:80]:
Platform does not support MT-full

8 runs, 25 assertions, 0 failures, 0 errors, 1 skips
```

``` bash
Node under test:
  - name  - n56-136
  - type  - N5K-C56128P
  - image - bootflash:///n6000-uk9.7.3.0.N1.1.bin

TestFeature#test_tacacs = 4.86 s = .
TestFeature#test_vn_segment_vlan_based = 8.14 s = .
TestFeature#test_vtp = 3.92 s = .
TestFeature#test_feature_set_fex = 1.02 s = .
TestFeature#test_bgp = 4.49 s = .
TestFeature#test_pim = 2.95 s = .
TestFeature#test_nv_overlay_evpn = 2.35 s = .
TestFeature#test_fabric_forwarding = 2.24 s = S
TestFeature#test_ospf = 4.57 s = .
TestFeature#test_vni = 3.07 s = .
TestFeature#test_nv_overlay = 133.21 s = .
TestFeature#test_feature_set_fabric = 56.22 s = .
TestFeature#test_private_vlan = 4.00 s = .

Finished in 233.491667s, 0.0557 runs/s, 0.1970 assertions/s.

  1) Skipped:
TestFeature#test_fabric_forwarding [test_feature.rb:89]:
This feature is only supported on 7.0(3)I2 images

13 runs, 46 assertions, 0 failures, 0 errors, 1 skips
```

### Errors

Only error I found was on N9kv and seems unrelated:

``` bash
  1) Error:
TestVxlanVtep#test_source_interface_hold_down_time:
Cisco::CliError: [#<Cisco::VxlanVtep:0x00000001e90128>] The command ' source-interface hold-down-time 50' was rejected with error:
Invalid interface format

    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/client/nxapi/client.rb:276:in `handle_output'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/client/nxapi/client.rb:203:in `block in req'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/client/nxapi/client.rb:202:in `zip'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/client/nxapi/client.rb:202:in `req'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/client/nxapi/client.rb:116:in `set'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/node.rb:197:in `set'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/node.rb:137:in `config_set'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:72:in `config_set'
    /home/robgrie/cisco-network-node-utils/lib/cisco_node_utils/vxlan_vtep.rb:155:in `source_interface_hold_down_time='
    test_vxlan_vtep.rb:227:in `test_source_interface_hold_down_time'
```

**Comment by robert-w-gries** [comment]
Grrr some other changes got pulled in somehow. Let me fix them

**Pull request closed without merging**
