### PR TITLE
Added allocate_label_all and as_path_loopcheck_out

### PR DESCRIPTION
**Pull request by brturn**
Upgraded the test exceptions checker to prioritize unsupported errors over CliErrors.

### CODE REVIEW

**Comment by mikewiebe** [comment]
:+1:

**Comment by brturn** [comment]
I think this one is ready.  It gathered some scope creep, but the presentation of properties_matrix is much nicer now, and moved into CiscoTest base class. @mikewiebe @chburket @glennmatthews

**Comment by mikewiebe** [comment]
@brturn Is this still something we need to try and get merged or can we close this?

**Comment by chrisvanheuveln** [comment]
This has been idle for a couple of weeks so closing it for now.

**Pull request closed without merging**
