### PR TITLE
Added EXR support for ntp_server

### PR DESCRIPTION
**Pull request by jonnytdevops**

### CODE REVIEW

**Comment by jonnytdevops** [comment]
```
$ /opt/puppetlabs/puppet/bin/puppet resource ntp_server
ntp_server { '10.240.0.10':
  ensure => 'present',
  prefer => 'false',
}
ntp_server { '2.2.2.2':
  ensure => 'present',
  prefer => 'true',
}
ntp_server { '3.3.3.3':
  ensure => 'present',
  prefer => 'true',
}
ntp_server { '4.4.4.4':
  ensure => 'present',
  prefer => 'false',
}
```

```
RP/0/RP0/CPU0:yb4qczdsv44wb36#show running-config ntp
Mon Feb 15 16:33:58.822 UTC
ntp
 server 2.2.2.2 prefer
 server 3.3.3.3 prefer
 server 4.4.4.4
 server 10.240.0.10
!
```

**Comment by glennmatthews** [comment]
Consider extracting some of the common logic into a `_template` section so you don't have to repeat yourself as much in the YAML.

**Comment by glennmatthews** [comment]
Looks good to me - please run minitest against XR and provide the results, then I'll be happy to merge it.

**Comment by jonnytdevops** [comment]
@glennmatthews I've updated the YAML file to use _template. I still can't get the minitests running though:

```
getaddrinfo: nodename nor servname provided, or not known
```

**Comment by glennmatthews** [comment]
Minitest passes against Nexus:

```
Node under test:
  - name  - n9k-108
  - type  - N9K-C9396PX
...

Finished in 8.997895s, 0.3334 runs/s, 3.2230 assertions/s.

3 runs, 29 assertions, 0 failures, 0 errors, 0 skips
```

Gathering XR results now.

**Comment by glennmatthews** [comment]
This blows up with IPv6 servers on XR:

```
ntp
 server 130.88.203.12
 server ipv6 2003::5 prefer
!
```

It tries to recognize 'ipv6' as a server address, and dies with the below error:

```
TestNtpServer#test_ntpserver_create_destroy_single_ipv6:
ArgumentError: Invalid value (Name is not a valid single IPv4/IPv6 address)
    ...lib/cisco_node_utils/ntp_server.rb:37:in `rescue in initialize'
```

**Comment by jonnytdevops** [comment]
@glennmatthews Code updated for ipv6 on exr. It's quite hacky, so your feedback would be appreciated if I'm going to do this with the other providers. Thanks

**Comment by jonnytdevops** [comment]
@glennmatthews The hackyness lies in the fact that config_get returns a format like this:

```
[[nil, "2.2.2.2"], [nil, "3.3.3.3"], [nil, "4.4.4.4"], [nil, "8.8.8.8"], [nil, "10.240.0.10"], ["ipv6 ", "2003::4"], ["ipv6 ", "2004::3"]]
```

I couldn't find any other regex that was neater.

**Comment by glennmatthews** [comment]
I think you can simplify the hackyness by making the ipv6 a non-capturing group with the `(?:...)` magic (http://ruby-doc.org/core-2.1.4/Regexp.html#class-Regexp-label-Grouping):

 `/server (?:ipv6 )?(\S+) prefer/`
`/server (?:ipv6 )?(\S+)/`

**Comment by jonnytdevops** [comment]
@glennmatthews Fantastic!! That worked really well. Code updated :)

Thanks

**Comment by glennmatthews** [comment]
I had to make one fix in the test script - will commit this separately. Besides this fix, now passes on XR. Thanks!

``` diff
diff --git a/tests/test_ntp_server.rb b/tests/test_ntp_server.rb
index 7e2fdb7..b6a71c2 100644
--- a/tests/test_ntp_server.rb
+++ b/tests/test_ntp_server.rb
@@ -34,8 +34,8 @@ class TestNtpServer < CiscoTestCase

   def no_ntpserver_uk
     # Turn the feature off for a clean test.
-    config('no ntpserver 130.88.203.12',
-           'no ntpserver 2003::5')
+    config('no ntp server 130.88.203.12',
+           'no ntp server 2003::5')
   end
```

**Comment by glennmatthews** [comment]
test fix committed in fbd4d5b

**Pull request merged**
