### PR TITLE
1.fixed rubocop errors and 2.fixed n5k test failure

### PR DESCRIPTION
**Pull request by dcheriancisco**
Ran rubocop against three files:
1. fabricpath_global.rb
2. fabricpath_topology.rb
3. test_fabricapth_global.rp
and fixed all errors
In the process, also fixed n5k testcase failure

### CODE REVIEW

**Comment by mikewiebe** [comment]
@dcheriancisco Still have 5 rubocop failures.. do you want to take care of those as well or do that in a subsequent commit?

**Comment by dcheriancisco** [comment]
I will take of this first, Mike

Thx,
deepak

**Comment by chrisvanheuveln** [comment]
Deepak - changes look fine. I'll wait for your remaining rubocop fixes before merging.

**Comment by dcheriancisco** [comment]
Chris and Mike,

I have this error only now:

node.rb:73:5: C: Assignment Branch Condition size for config_get is too high. [47.7/47]
    def config_get(feature, name, *args)
    ^^^

I had added one line to node.rb due to which this is showing up.

I am thinking of disabling the AbcSize cop for this method

# rubocop:disable Metrics/AbcSize

Is that OK?

Thx,
deepak

**Comment by dcheriancisco** [comment]
# N5k minitest results:

$ minitest ./test_fabricpath_global.rb 10.122.84.136 admin
Run options: -v -- --seed 7536

# Running:

Node under test:
- name  - n8k-136
- type  - N5K-C56128P
- image - bootflash:///n6000-uk9.7.3.0.N1.0.2.bin

TestFabricpathGlobal#test_global_destroy = 82.56 s = .
TestFabricpathGlobal#test_aggregate_multicast_routes = 49.78 s = .
TestFabricpathGlobal#test_transition_delay = 48.76 s = .
TestFabricpathGlobal#test_graceful_merge = 45.75 s = .
TestFabricpathGlobal#test_global_collection_empty = 3.00 s = .
TestFabricpathGlobal#test_loadbalance_multicast = 44.21 s = .
TestFabricpathGlobal#test_switch_id = 49.79 s = .
TestFabricpathGlobal#test_mode = 46.28 s = .
TestFabricpathGlobal#test_global_create = 45.32 s = .
TestFabricpathGlobal#test_linkup_delay_all = 49.11 s = .
TestFabricpathGlobal#test_allocate_delay = 46.79 s = .
TestFabricpathGlobal#test_loadbalance_algorithm = 45.24 s = .
TestFabricpathGlobal#test_loadbalance_unicast = 45.73 s = .

Finished in 602.310137s, 0.0216 runs/s, 0.0432 assertions/s.

13 runs, 26 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /ws/dcherian-sjc/git_projects/develop/cisco-network-node-utils/tests/coverage. 0.0 / 0.0 LOC (100.0%) covered.

# N7k minitest results:

$ minitest ./test_fabricpath_global.rb 172.23.149.210 nbv_12345
Run options: -v -- --seed 64946

# Running:

Node under test:
- name  - n7700
- type  - N77-C7710
- image - bootflash:///n7700-s2-dk9.7.3.0.OAC.0.7.gbin

TestFabricpathGlobal#test_linkup_delay_all = 54.37 s = .
TestFabricpathGlobal#test_loadbalance_multicast = 33.40 s = .
TestFabricpathGlobal#test_global_collection_empty = 1.29 s = .
TestFabricpathGlobal#test_global_create = 27.50 s = .
TestFabricpathGlobal#test_allocate_delay = 32.53 s = .
TestFabricpathGlobal#test_aggregate_multicast_routes = 27.10 s = .
TestFabricpathGlobal#test_graceful_merge = 33.40 s = .
TestFabricpathGlobal#test_global_destroy = 23.12 s = .
TestFabricpathGlobal#test_switch_id = 33.04 s = .
TestFabricpathGlobal#test_loadbalance_algorithm = 33.07 s = .
TestFabricpathGlobal#test_mode = 27.28 s = .
TestFabricpathGlobal#test_transition_delay = 33.04 s = .
TestFabricpathGlobal#test_loadbalance_unicast = 34.71 s = .

Finished in 393.848697s, 0.0330 runs/s, 0.0939 assertions/s.

13 runs, 37 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /ws/dcherian-sjc/git_projects/develop/cisco-network-node-utils/tests/coverage. 0.0 / 0.0 LOC (100.0%) covered.

$ type minitest
minitest is a function
minitest () 
{ 
    if [ "x$4" != "x" ]; then
        testcase="--name=$4";
    else
        testcase="";
    fi;
    ruby $1 -v -- $testcase $2 admin $3
}

**Comment by chrisvanheuveln** [comment]
Just bump up the AbcSize value to 48  in lib/.rubocop.yml

```
Metrics/AbcSize:
  Max: 48
```

**Comment by dcheriancisco** [comment]
changed AbcSize to 48 in lib/.rubocop.yml and removed the # rubocop:disable Metrics/AbcSize from node.rb

**Pull request merged**
