### PR TITLE
Add spec checking whitespace in non-Ruby files

### PR DESCRIPTION
**Pull request by glennmatthews**
Counterpart to #280 - add a Rake task to check for whitespace, so that we get validation in Travis-CI as well. This will show a lot of failures - #279 is fixing a number of them but there may be a number left over still.

### CODE REVIEW

**Comment by mikewiebe** [comment]
Are you also planning to fix the whitespace issues in this commit or do you want to commit without them?

**Comment by glennmatthews** [comment]
Gonna fix the remaining issues now that #279 has been merged. Thanks for checking.

**Comment by mikewiebe** [comment]
:+1:

**Comment by robert-w-gries** [comment]
:+1:

**Pull request merged**
