### PR TITLE
Added tacacs_server_group

### PR DESCRIPTION
**Pull request by jonnytdevops**
Exactly the same as radius_server_group, which has been merged

### CODE REVIEW

**Comment by glennmatthews** [comment]
Can you provide minitest results please?

**Comment by jonnytdevops** [comment]
$ bundle exec ruby tests/test_tacacs_server_group.rb -v -- 10.168.1.3 admin admin
Run options: -v -- --seed 47561

# Running:

Node under test:
- name  - switch
- type  - N9K-NXOSV
- image - bootflash:///nxos.7.0.3.I2.1.bin

TestTacacsServerGroup#test_create_destroy_multiple = 18.03 s = .
TestTacacsServerGroup#test_create_destroy_single = 15.04 s = .

Finished in 33.070893s, 0.0605 runs/s, 0.9071 assertions/s.

2 runs, 30 assertions, 0 failures, 0 errors, 0 skips

**Comment by glennmatthews** [comment]
Is this redundant with the aaa_server_group class in feature/aaa branch?

https://github.com/cisco/cisco-network-node-utils/blob/2deb0720536c11f38b28fe3f89d87218913ed66f/lib/cisco_node_utils/aaa_server_group.rb

**Comment by jonnytdevops** [comment]
@glennmatthews This was never mentioned to me at any previous meeting, and I just followed the same design as radius_server_group, which has already been merged.

**Comment by jonnytdevops** [comment]
@glennmatthews I also can't see AaaServerGroup this in the develop branch, hence I was unable to use it. As such, in my opinion, both of these things are up for merge in to develop. Since we're implementing for NetDev and we like to keep parity between util gem and puppet provider, I still feel this class is still needed.

Thanks

**Comment by hunsbea** [comment]
Just comparing this implementation to the one in feature/aaa, this one seems to be missing the vrf, source_interface, and deadtime properties. @jonnytpuppet with regard to parity between node utils and puppet, I have puppet code out for review here: https://github.com/cisco/cisco-network-puppet-module/pull/56/

If you want to keep this version, maybe you can use my code as a guide to implement what's missing. Otherwise, is there any reason to have both a Netdev and Cisco implementation?

Edit: I just discussed with Sanjay/Mike and it's fine to keep separate provider/types, but we should merge the node utils objects so both of our puppet implementations can use it.

**Comment by jonnytdevops** [comment]
@hunsbea We are implementing providers for use with the Puppet Labs netdev module. This only supports a particular subset of properties available on the device (and in some cases, vice versa). In this case, netdev's tacacs_server_group only has one property: servers

We remain parity to keep our scoping limited to NetDev, otherwise further design discussions and documents are required. In this case, I don't have an issue in using your one, but it's not available in the develop branch so I can't use it. However, I think it should be called tacacs_server_group.rb, in line with radius_server_group.rb which has already been merged.

Thanks

**Comment by jonnytdevops** [comment]
@mikewiebe @glennmatthews Is there any update to this? Do you need me to do anything?

Thanks

**Comment by glennmatthews** [comment]
I'm OK with merging this for now with the understanding that we'll have to resolve the duplication between tacacs_server_group and aaa_server_group before the next release of cisco_node_utils.

**Comment by mikewiebe** [comment]
:+1:  Based on @glennmatthews comments about resolving duplication with @hunsbea's version of the object.

**Comment by hunsbea** [comment]
:+1:

**Comment by mikewiebe** [comment]
@jonnytpuppet I am working to merge this now.

**Comment by mikewiebe** [comment]
@jonnytpuppet 

Can you add me as a contributor for your https://github.com/jonnytpuppet/cisco-network-node-utils repo?

I have fixed all of the merge conflicts for this PR but cannot push the updates.

Thanks!

**Pull request merged**
