### PR TITLE
Fix similar vlan id issue

### PR DESCRIPTION
**Pull request by mikewiebe**
**Summary:** This fixes a defect when using structured output.  If multiple row index's exist that have simlar data, we will match on the last index found and overwrite any previously discovered data.  This fix ensures we do an exact match on keys supplied by the yaml file for structured output queries.

**Problem demonstration**

```
[4] pry(#<TestVlan>)> v2 = Vlan.new(2)
=> #<Cisco::Vlan:0x007fe245e413b0 @vlan_id="2">
[5] pry(#<TestVlan>)> v102 = Vlan.new(102)
=> #<Cisco::Vlan:0x007fe245dd2050 @vlan_id="102">
[6] pry(#<TestVlan>)> 
[7] pry(#<TestVlan>)> v2.vlan_name = "MIKE"
=> "MIKE"
[8] pry(#<TestVlan>)> v102.vlan_name = "BOB"
=> "BOB"
[9] pry(#<TestVlan>)> 
[10] pry(#<TestVlan>)> v2.vlan_name
=> "BOB"
[12] pry(#<TestVlan>)> v102.vlan_name
=> "BOB"
[13] pry(#<TestVlan>)> 
```
As you can see above both v2 and v102 are updated with the vlan_name "BOB"

**Behavior with fix applied**

```irb
[3] pry(#<TestVlan>)> v2 = Vlan.new(2)
=> #<Cisco::Vlan:0x007f068744d358 @vlan_id="2">
[4] pry(#<TestVlan>)> v102 = Vlan.new(102)
=> #<Cisco::Vlan:0x007f0686f811f8 @vlan_id="102">
[5] pry(#<TestVlan>)> v2.vlan_name = "MIKE"
=> "MIKE"
[6] pry(#<TestVlan>)> v102.vlan_name = "BOB"
=> "BOB"
[7] pry(#<TestVlan>)> v2.vlan_name
=> "MIKE"
[8] pry(#<TestVlan>)> v102.vlan_name
=> "BOB"
[9] pry(#<TestVlan>)> 
```

**Testing**
 * `test_vlan.rb` and `test_snmpcommunity.rb` run against `n3k, n9k, n9k-f and n7k`
 * Full minitest regression in progress against `n9k`

**I2.2e Test Results:**
```
+------------------------------------------------------------------------------+
|                             Task Result Details                              |
+------------------------------------------------------------------------------+
AgentsTests: agents
|-- minitests                                                             PASSED
|   |-- setupDeviceConnect                                                PASSED
|   |   |-- Step 1: Connect to Agent                                      PASSED
|   |   `-- Step 2: Connect to Workstation                                PASSED
|   |-- setupWS                                                           PASSED
|   |   |-- Step 1: Clean & Clone Repo (NU)                               PASSED
|   |   |-- Step 1.1: Purge Existing Repo Data                            PASSED
|   |   |-- Step 1.2: Clone Repo                                          PASSED
|   |   `-- Step 1.3: Checkout Repo Branch: (rel160/vlan_name_fix)        PASSED
|   |-- runMinitestTests                                                  PASSED
|   `-- cleanup                                                           PASSED
|-- minitest_results[suite=./test_vlan.rb]                                PASSED
|   `-- report                                                            PASSED
```

**I4.5 Test Results:**
```
+------------------------------------------------------------------------------+
|                             Task Result Details                              |
+------------------------------------------------------------------------------+
AgentsTests: agents
|-- minitests                                                             PASSED
|   |-- setupDeviceConnect                                                PASSED
|   |   |-- Step 1: Connect to Agent                                      PASSED
|   |   `-- Step 2: Connect to Workstation                                PASSED
|   |-- setupWS                                                           PASSED
|   |   |-- Step 1: Clean & Clone Repo (NU)                               PASSED
|   |   |-- Step 1.1: Purge Existing Repo Data                            PASSED
|   |   |-- Step 1.2: Clone Repo                                          PASSED
|   |   `-- Step 1.3: Checkout Repo Branch: (rel160/vlan_name_fix)        PASSED
|   |-- runMinitestTests                                                  PASSED
|   `-- cleanup                                                           PASSED
|-- minitest_results[suite=./test_vlan.rb]                                PASSED
|   `-- report                                                            PASSED
```

**I5.1 Test Results:**
```
+------------------------------------------------------------------------------+
|                             Task Result Details                              |
+------------------------------------------------------------------------------+
AgentsTests: agents
|-- minitests                                                             PASSED
|   |-- setupDeviceConnect                                                PASSED
|   |   |-- Step 1: Connect to Agent                                      PASSED
|   |   `-- Step 2: Connect to Workstation                                PASSED
|   |-- setupWS                                                           PASSED
|   |   |-- Step 1: Clean & Clone Repo (NU)                               PASSED
|   |   |-- Step 1.1: Purge Existing Repo Data                            PASSED
|   |   |-- Step 1.2: Clone Repo                                          PASSED
|   |   `-- Step 1.3: Checkout Repo Branch: (rel160/vlan_name_fix)        PASSED
|   |-- runMinitestTests                                                  PASSED
|   `-- cleanup                                                           PASSED
|-- minitest_results[suite=./test_vlan.rb]                                PASSED
|   `-- report                                                            PASSED
```

**I5.2 Test Results:**
```
+------------------------------------------------------------------------------+
|                             Task Result Details                              |
+------------------------------------------------------------------------------+
AgentsTests: agents
|-- minitests                                                             PASSED
|   |-- setupDeviceConnect                                                PASSED
|   |   |-- Step 1: Connect to Agent                                      PASSED
|   |   `-- Step 2: Connect to Workstation                                PASSED
|   |-- setupWS                                                           PASSED
|   |   |-- Step 1: Clean & Clone Repo (NU)                               PASSED
|   |   |-- Step 1.1: Purge Existing Repo Data                            PASSED
|   |   |-- Step 1.2: Clone Repo                                          PASSED
|   |   `-- Step 1.3: Checkout Repo Branch: (rel160/vlan_name_fix)        PASSED
|   |-- runMinitestTests                                                  PASSED
|   `-- cleanup                                                           PASSED
|-- minitest_results[suite=./test_vlan.rb]                                PASSED
|   `-- report                                                            PASSED
```
**Full minitest results:**
```
Overall Stats
    Passed     : 76
    Passx      : 0
    Failed     : 0
    Aborted    : 0
    Blocked    : 0
    Skipped    : 18
    Errored    : 0

    TOTAL      : 94

Success Rate   : 100.00 %
```

### CODE REVIEW

**Comment by mikewiebe** [comment]
@tomcooperca Here is the cadidate fix for the vlan_name problem you demonstrated last week.  Once we have complete test results we will merge into our `develop` branch.

**Comment by saichint** [comment]
is this similar to double quotes issue (but in the structured output) ?

@saichint No, not really.  The problem occurs because we are attempting to find the correct row in the structured output, but we were not looking for an exact match when searching for the row.  We were only checking to make sure the row contained the key which could result in multiple matches.

The reason I changed the get_value to: `get_value: ["name \"Chassis\"", "serialnum"]` is because that is what gets returned in the structured output and this update ensures we do an exact match.  I am testing I2 -> I5 images to make sure this is consistent for the `Chassis` key.

```
{
  "ins_api": {
    "type": "cli_show",
    "version": "1.0",
    "sid": "eoc",
    "outputs": {
      "output": {
        "input": "show inventory",
        "msg": "Success",
        "code": "200",
        "body": {
          "TABLE_inv": {
            "ROW_inv": [
              {
                "name": "\"Chassis\"",
                "desc": "\"Nexus 3048 Chassis\"",
                "productid": "N3K-C3048TP-1GE",
                "vendorid": "V01",
                "serialnum": "FOC1723R1LC"
              },
              {
                "name": "\"Slot 1\"",
                "desc": "\"48x1GE + 4x10G Supervisor\"",
                "productid": "N3K-C3048TP-1GE",
                "vendorid": "V01",
                "serialnum": "FOC17230FB4"
              },
              {
                "name": "\"Power Supply 1\"",
                "desc": "\"Nexus 3048 Chassis Power Supply\"",
                "productid": "N2200-PAC-400W",
                "vendorid": "V04",
                "serialnum": "LIT17090Q7R"
              },
              {
                "name": "\"Power Supply 2\"",
                "desc": "\"Nexus 3048 Chassis Power Supply\"",
                "productid": "N2200-PAC-400W",
                "vendorid": "V04",
                "serialnum": "LIT17130YT6"
              },
              {
                "name": "\"Fan 1\"",
                "desc": "\"Nexus 3048 Chassis Fan Module\"",
                "productid": "N3K-C3064-FAN",
                "vendorid": "V00",
                "serialnum": "N/A"
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by saichint** [comment]
Also do we need to run beaker tests for vlan provider ?

@saichint Probably.  This should not impact the provider tests but let's be safe :)  I will queue the tests and have the results in a few hours.  The minitests are currently in progress.

Beaker test results for vlan provider:

```
 222558: ./cisco_vlan/test_vlan.rb passed in 274.63 seconds
 222559:       Test Suite: tests @ 2017-03-14 00:34:29 -0400
222560: 
 222561:       - Host Configuration Summary -
222562: 
222563: 
 222564:               - Test Case Summary for suite 'tests' -
 222565:        Total Suite Time: 274.63 seconds
 222566:       Average Test Time: 274.63 seconds
 222567:               Attempted: 1
 222568:                  Passed: 1
 222569:                  Failed: 0
 222570:                 Errored: 0
 222571:                 Skipped: 0
 222572:                 Pending: 0
 222573:                   Total: 1
222574: 
 222575:       - Specific Test Case Status -
```

**Comment by ghost** [comment]
@mikewiebe Looks good! Thanks for the quick turnaround.

**Review by rahushen — APPROVED** [review]
Changes look good.

**Comment by saichint** [comment]
:+1:

**Pull request merged**
