### PR TITLE
bestpath_med_confed is not valid with a vrf on XR

### PR DESCRIPTION
**Pull request by chburket**

### CODE REVIEW

**Comment by glennmatthews** [comment]
Any change to the minitest required?

**Comment by chburket** [comment]
Good catch.  I updated the minitest.

**Comment by glennmatthews** [comment]
Please fix rubocop failure:

```
tests/test_router_bgp.rb:288:13: C: Align the parameters of a method call if they span more than one line.

            'bgp bestpath_med_confed should be disabled')

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

102 files inspected, 1 offense detected

RuboCop failed!
```

**Comment by chburket** [comment]
@glennmatthews 
Fixed rubocop error.

**Comment by RichWellum** [comment]
Thanks Charles - will merge this now.

**Pull request merged**
