### PR TITLE
(NETDEV-37) Add support for hostname

### PR DESCRIPTION
**Pull request by willmeek**
This commit adds a hostname provider, with a name string field.

### CODE REVIEW

**Comment by willmeek** [comment]
Customer request. Requires the release of netdev-stdlib and the merging of https://github.com/cisco/cisco-network-puppet-module/pull/511

**Comment by willmeek** [comment]
Closing this PR temporarily, we have changed the approach to hostname in netdev stdlib, need to rejig the logic here and reopen.

Edit - Reopened, it appears that network_dns provider uses seperate node util classes for fields, we can leave this as is.

**Comment by shermdog** [comment]
:+1:

**Comment by saichint** [comment]
👍

**Comment by shermdog** [comment]
@willmeek can you add CHANGELOG for this?

**Comment by willmeek** [comment]
@shermdog Added a note to changelog, though the way it is structured is slightly different to netdev stdlib network_dns

**Pull request merged**
