### PR TITLE
version may be absent on 'snmp-server host'

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@chburket @mikewiebe i found a case where by an snmp-server host, may not have version set, eg

snmp-server host 2.3.4.5 traps ab udp-port 47
vs
snmp-server host 4.5.6.7 informs version 3 priv ab udp-port 45

The regex was too strict in the yaml. it does not need version.

Run options: -v -- --seed 62404

# Running:

Node under test:
- name  - ufmmc7dul2110rj
- type  - R-IOSXRV9000-CH
- image - 6.0.0.20I

TestSnmpNotificationReceiver#test_create_destroy_single = 69.51 s = .
TestSnmpNotificationReceiver#test_create_destroy_multiple = 102.59 s = .
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 79.18 s = .

Finished in 265.354259s, 0.0113 runs/s, 0.2073 assertions/s.

3 runs, 55 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /Users/tp/workspace/git/EXR/cisco_devenv/cisco-network-node-utils/coverage. 2476 / 4995 LOC (49.57%) covered.

**Comment by mikewiebe** [comment]
@tphoney Can you include results on NXOS?

**Update:** Never mind, I am running them now.

**Comment by mikewiebe** [comment]
@tphoney I just ran tests on a couple of Nexus platforms and see some issues.  I compared the results with develop though and see some failures there as well, but they are different.  Let's  make sure the tests are passing on both nxos and xr in your private branch before we merge.

Here are the results:

```
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> git checkout version_may_not_be_set
Branch version_may_not_be_set set up to track remote branch version_may_not_be_set from origin.
Switched to a new branch 'version_may_not_be_set'
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> ruby tests/test_snmp_notification_receiver.rb -e n3k -v
Run options: -e n3k -v --seed 18536

# Running:


Node under test:
  - name  - n3x-163
  - type  - N3K-C3172PQ-10GE
  - image - bootflash:///nxos.7.0.3.I2.3.bin

TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 3.65 s = E
TestSnmpNotificationReceiver#test_create_destroy_single = 2.73 s = E
TestSnmpNotificationReceiver#test_create_destroy_multiple = 1.83 s = F

Finished in 9.514847s, 0.3153 runs/s, 1.6816 assertions/s.

  1) Error:
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6:
RuntimeError: Expected zero/one value but got '["45", "45"]'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:72:in `massage'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:60:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:48:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/snmp_notification_receiver.rb:131:in `port'
    tests/test_snmp_notification_receiver.rb:99:in `test_create_destroy_single_ipv6'


  2) Error:
TestSnmpNotificationReceiver#test_create_destroy_single:
RuntimeError: Expected zero/one value but got '["45", "45"]'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:72:in `massage'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:60:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:48:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/snmp_notification_receiver.rb:131:in `port'
    tests/test_snmp_notification_receiver.rb:68:in `test_create_destroy_single'


  3) Failure:
TestSnmpNotificationReceiver#test_create_destroy_multiple [tests/test_snmp_notification_receiver.rb:115]:
Expected {"2004::7"=>#<Cisco::SnmpNotificationReceiver:0x007f9317ffd780 @name="2004::7">} to not include "2004::7".

3 runs, 16 assertions, 1 failures, 2 errors, 0 skips
Coverage report generated for MiniTest to /nobackup/mwiebe/NU/tp/cisco-network-node-utils/coverage. 1324 / 2890 LOC (45.81%) covered.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> ruby tests/test_snmp_notification_receiver.rb -e n3k -v
Run options: -e n3k -v --seed 6493

# Running:


Node under test:
  - name  - n3x-163
  - type  - N3K-C3172PQ-10GE
  - image - bootflash:///nxos.7.0.3.I2.3.bin

TestSnmpNotificationReceiver#test_create_destroy_single = 4.46 s = .
TestSnmpNotificationReceiver#test_create_destroy_multiple = 1.77 s = F
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 1.77 s = F

Finished in 9.323408s, 0.3218 runs/s, 2.1451 assertions/s.

  1) Failure:
TestSnmpNotificationReceiver#test_create_destroy_multiple [tests/test_snmp_notification_receiver.rb:115]:
Expected {"2004::7"=>#<Cisco::SnmpNotificationReceiver:0x007faba49f6c10 @name="2004::7">} to not include "2004::7".


  2) Failure:
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 [tests/test_snmp_notification_receiver.rb:81]:
Expected {"2004::7"=>#<Cisco::SnmpNotificationReceiver:0x007faba486d880 @name="2004::7">} to not include "2004::7".

3 runs, 20 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /nobackup/mwiebe/NU/tp/cisco-network-node-utils/coverage. 1333 / 2890 LOC (46.12%) covered.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> git checkout version_may_not_be_set
Switched to branch 'version_may_not_be_set'
Your branch is up-to-date with 'origin/version_may_not_be_set'.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> ruby tests/test_snmp_notification_receiver.rb -e n5k -v
Run options: -e n5k -v --seed 28847

# Running:


Node under test:
  - name  - n56-136
  - type  - N5K-C56128P
  - image - bootflash:///n6000-uk9.7.3.1.N1.1.bin

TestSnmpNotificationReceiver#test_create_destroy_multiple = 8.70 s = E
TestSnmpNotificationReceiver#test_create_destroy_single = 2.32 s = E
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 2.35 s = E

Finished in 15.618709s, 0.1921 runs/s, 1.2805 assertions/s.

  1) Error:
TestSnmpNotificationReceiver#test_create_destroy_multiple:
RuntimeError: Expected zero/one value but got '["45", "45", "45"]'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:72:in `massage'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:60:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:48:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/snmp_notification_receiver.rb:131:in `port'
    tests/test_snmp_notification_receiver.rb:144:in `test_create_destroy_multiple'


  2) Error:
TestSnmpNotificationReceiver#test_create_destroy_single:
RuntimeError: Expected zero/one value but got '["45", "45", "45"]'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:72:in `massage'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:60:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:48:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/snmp_notification_receiver.rb:131:in `port'
    tests/test_snmp_notification_receiver.rb:68:in `test_create_destroy_single'


  3) Error:
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6:
RuntimeError: Expected zero/one value but got '["45", "45", "45"]'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:72:in `massage'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node.rb:60:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/node_util.rb:48:in `config_get'
    /nobackup/mwiebe/NU/tp/cisco-network-node-utils/lib/cisco_node_utils/snmp_notification_receiver.rb:131:in `port'
    tests/test_snmp_notification_receiver.rb:99:in `test_create_destroy_single_ipv6'

3 runs, 20 assertions, 0 failures, 3 errors, 0 skips
Coverage report generated for MiniTest to /nobackup/mwiebe/NU/tp/cisco-network-node-utils/coverage. 1324 / 2890 LOC (45.81%) covered.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> git checkout develop
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> ruby tests/test_snmp_notification_receiver.rb -e n5k -v
Run options: -e n5k -v --seed 9482

# Running:


Node under test:
  - name  - n56-136
  - type  - N5K-C56128P
  - image - bootflash:///n6000-uk9.7.3.1.N1.1.bin

TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 1.68 s = F
TestSnmpNotificationReceiver#test_create_destroy_single = 3.43 s = .
TestSnmpNotificationReceiver#test_create_destroy_multiple = 1.73 s = F

Finished in 8.943646s, 0.3354 runs/s, 2.2362 assertions/s.

  1) Failure:
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 [tests/test_snmp_notification_receiver.rb:81]:
Expected {"2004::7"=>#<Cisco::SnmpNotificationReceiver:0x007fcc6228f0d8 @name="2004::7">} to not include "2004::7".


  2) Failure:
TestSnmpNotificationReceiver#test_create_destroy_multiple [tests/test_snmp_notification_receiver.rb:115]:
Expected {"2004::7"=>#<Cisco::SnmpNotificationReceiver:0x007fcc6243c688 @name="2004::7">} to not include "2004::7".

3 runs, 20 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /nobackup/mwiebe/NU/tp/cisco-network-node-utils/coverage. 1333 / 2890 LOC (46.12%) covered.
rtp-ads-075:/nobackup/mwiebe/NU/tp/cisco-network-node-utils> 
```

**Comment by tphoney** [comment]
This will take at least half a day to setup. :( I will look into it on monday.

**Comment by tphoney** [comment]
Run options: -v -- --seed 50479

# Running:

Node under test:
- name  - switch
- type  - N9K-NXOSV
- image - bootflash:///nxos.7.0.3.I2.1.bin

TestSnmpNotificationReceiver#test_create_destroy_single = 13.41 s = .
TestSnmpNotificationReceiver#test_create_destroy_multiple = 13.79 s = .
TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 13.20 s = .

Finished in 41.580335s, 0.0721 runs/s, 1.3468 assertions/s.

3 runs, 56 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /Users/tp/workspace/machines/cisco/cisco_devenv/cisco-network-node-utils/coverage. 2369 / 5014 LOC (47.25%) covered.

Run options: -v -- --seed 23694

# Running:

Node under test:
- name  - ldv6kkd8odvbueu
- type  - R-IOSXRV9000-CH
- image - 6.0.0.20I

TestSnmpNotificationReceiver#test_create_destroy_single_ipv6 = 25.64 s = .
TestSnmpNotificationReceiver#test_create_destroy_single = 22.28 s = .
TestSnmpNotificationReceiver#test_create_destroy_multiple = 31.00 s = .

Finished in 84.472391s, 0.0355 runs/s, 0.6511 assertions/s.

3 runs, 55 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for MiniTest to /Users/tp/workspace/git/EXR/cisco_devenv/cisco-network-node-utils/coverage. 2476 / 4995 LOC (49.57%) covered.

**Comment by tphoney** [comment]
@mikewiebe @chburket I have made the changes needed, and the passing test results for nexus and ios are above.

**Comment by chburket** [comment]
:+1:

**Comment by tphoney** [comment]
@mikewiebe can i get a merge :)

**Comment by mikewiebe** [comment]
👍

**Pull request merged**
