### PR TITLE
Fix last_reset check for platform

### PR DESCRIPTION
**Pull request by robert-w-gries**
Follow-up to #443 that fixes `TestPlatform`

### CODE REVIEW

**Comment by mikewiebe** [comment]
Do we need this fix in `develop` also?

**Comment by robert-w-gries** [comment]
Yes.  I assume the plan is to merge `release` branch into `develop` once the release is finished.

**Comment by mikewiebe** [comment]
True, but Chris has been making changes in develop and then cherry picking them into the release branch since it could be quite some time before we merge back into develop.  I would suggest you do the same.

**Comment by robert-w-gries** [comment]
Why don't we just merge `release_1.3.1` branch straight into `develop`? There shouldn't be a need for cherry-picking anything from release -> develop

**Comment by chrisvanheuveln** [comment]
Actually I was doing it the other way - I was working out of develop and then cherry-picking into 1.3.1.

But yeah merge would work too.

**Pull request merged**
