### PR TITLE
Add ntp server

### PR DESCRIPTION
**Pull request by jonnytdevops**
Hi Everyone,

Here is my initial contribution for adding support for ntp_server to the cisco network node util gem.

I recognise that I'll need to add a test before this can be merged, but any comment would be appreciated.

Thanks

JT (Jonny)
Puppet Labs

### CODE REVIEW

**Comment by jonnytdevops** [comment]
Here is the related Puppet Module provider: https://github.com/cisco/cisco-network-puppet-module/pull/7

**Comment by jonnytdevops** [comment]
The following netdev_stdlib PR is required for this to work correctly: https://github.com/puppetlabs/netdev_stdlib/pull/14

**Comment by hunner** [comment]
@jonnytpuppet Why is this closed?

**Comment by hunner** [comment]
Oh I see #5

**Pull request closed without merging**
