### PR TITLE
fix "weight" attribute setting.

### PR DESCRIPTION
**Pull request by HelenHZhang**
fix the broken beaker tests for "weight" for nexus.

### CODE REVIEW

**Comment by robert-w-gries** [comment]
Should this PR be merged into `develop` instead?

**Comment by chburket** [comment]
@robert-w-gries 

We're not sure if this is broken in develop.  There are other differences in the develop version of these files.  If a similar problem pops up when the full regression suite is run on develop, we can make a similar fix then.

**Comment by mikewiebe** [comment]
@chburket I verified that is is broken in `develop` so I agree with @robert-w-gries that it would be better to make the fix in develop and then merge develop into `feature/grpc`.

**Comment by HelenHZhang** [comment]
@robert-w-gries 
@mikewiebe 
I'll switch to develop branch, try the same fix, run all tests.
test_bgp_neighbor_af.rb is very different from develop branch and feature/grpc.

In develop branch, there is some n6k_platform, nk7_platform stuff, and no test_weight at all.
In feature/grpc branch, there is just "platform", and some xr stuff.

With just yaml file change, the beaker test passed at the test step
- TestStep :: 1.1 Default Properties :: IDEMPOTENCE" passed.

However, beaker tests failed at the test step:
- TestStep :: 5.12.1 Non Default Misc Map commands Part 1 [ensure => present] :: MANIFEST"

**Comment by mikewiebe** [comment]
@HelenHZhang Just fix the weight issue and we will take care of the additional beaker failures.

**Comment by HelenHZhang** [comment]
forgot adding test results:
The following tests passed.
1). minitest for test_bgp_neighbor_af on nexus
2). minitest for test_bgp_neighbor_af on xr
3). beaker tests for test_bgpneighborafon nexus

**Comment by glennmatthews** [comment]
@HelenHZhang Since #162 is merged, should we cancel this PR and just plan to merge latest develop code into feature/grpc?

**Comment by chburket** [comment]
@glennmatthews Seems reasonable to me.  I'm sure Helen will be ok with it.

**Pull request closed without merging**
